### ISSUE TITLE
TemplateNotFound due to slspath problem

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/chrony-formula#10]
Formula failed on Centos7 due to problem with #8 because `slspath+` cannot be rendered. Probably we need ` slspath +` instead (i.e. white spaces).

```
    Data failed to compile:
----------
    Rendering SLS 'base:chrony.init' failed: Jinja error: chrony/init/map.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 145, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: chrony/init/map.jinja

; line 1

---
{% from slspath+"/map.jinja" import chrony with context %}    <======================
```

**Comment by noelmcloughlin** [comment]
Might be related to: https://github.com/saltstack/salt/issues/41195 

```
TemplateNotFound: chrony/init/map.jinja

; line 1

---
{% from slspath + "/map.jinja" import chrony with context %}    <======================
```

**Comment by noelmcloughlin** [comment]
Hi @aboe76 should we revert [this commit](https://github.com/saltstack-formulas/chrony-formula/commit/d3444bb41b8a496063a94c76b3d3c33ec40ffb97)?

**Comment by noelmcloughlin** [comment]
Never mind @aboe76 - found the problem.
```
 include:
 -  - chrony
 +  - .init             <=============== This caused the issue```

**Comment by noelmcloughlin** [comment]
Thanks @aboe76
